version = 0.1

[default.deploy.parameters]
stack_name = "berry-setlist-matcher"
region = "ap-northeast-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
resolve_s3 = true
parameter_overrides = "HyperdriveApiUrl=https://d36w2d8blmdfr.cloudfront.net"
